export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILED = "GET_USERS_FAILED"

export const GET_LISTS_REQUESTED = "GET_LISTS_REQUESTED"
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS"
export const GET_LISTS_FAILED = "GET_LISTS_FAILED"

export const GET_LIST_REQUESTED = "GET_LIST_REQUESTED"
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS"
export const GET_LIST_FAILED = "GET_LIST_FAILED"

export const UPDATE_LIST_REQUESTED = "UPDATE_LIST_REQUESTED"
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS"
export const UPDATE_LIST_FAILED = "UPDATE_LIST_FAILED"

export const DELETE_LIST_REQUESTED = "DELETE_LIST_REQUESTED"
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS"
export const DELETE_LIST_FAILED = "DELETE_LIST_FAILED"

export const CREATE_LIST_REQUESTED = "CREATE_LIST_REQUESTED"
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAILED = "CREATE_LIST_FAILED"





export const GET_TODOS_REQUESTED = "GET_TODOS_REQUESTED"
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS"
export const GET_TODOS_FAILED = "GET_TODOS_FAILED"

export const GET_TODO_REQUESTED = "GET_TODO_REQUESTED"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAILED = "GET_TODO_FAILED"

export const UPDATE_TODO_REQUESTED = "UPDATE_TODO_REQUESTED"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"
export const UPDATE_TODO_FAILED = "UPDATE_TODO_FAILED"

export const DELETE_TODO_REQUESTED = "DELETE_TODO_REQUESTED"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED"

export const CREATE_TODO_REQUESTED = "CREATE_TODO_REQUESTED"
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS"
export const CREATE_TODO_FAILED = "CREATE_TODO_FAILED"



export const UPDATE_TODO_AS_DONE_REQUESTED = "UPDATE_TODO_AS_DONE_REQUESTED"
export const UPDATE_TODO_AS_DONE_SUCCESS = "UPDATE_TODO_AS_DONE_SUCCESS"
export const UPDATE_TODO_AS_DONE_FAILED = "UPDATE_TODO_AS_DONE_FAILED"